### ISSUE TITLE
`OSError: [Errno -9981] Input overflowed` After first transcription

### ISSUE THREAD

**Issue by joegoldin** [appvoid/vosper#2]
I'm trying to run Vosper on my M1 Macbook Pro and am getting the following error after the first transcription runs: 

```
- Testing, testing, one, two, three.
Traceback (most recent call last):
  File "/Users/jgoldin/Development/third_party/vosper/main.py", line 6, in <module>
    _input = listener.listen(mic, rec)
  File "/Users/jgoldin/Development/third_party/vosper/listener.py", line 36, in listen
    soundData = data.read(4096)
  File "/Users/jgoldin/miniconda3/envs/3.9/lib/python3.9/site-packages/pyaudio/__init__.py", line 570, in read
    return pa.read_stream(self._stream, num_frames,
OSError: [Errno -9981] Input overflowed
```

Here's a screencap:
![Screen Recording 2023-03-07 at 12 44 43 PM](https://user-images.githubusercontent.com/1571956/223549809-a64b2311-daf0-49d9-a89b-bce60685ce50.gif)
https://user-images.githubusercontent.com/1571956/223549835-6bac1bb2-7306-46a4-a3c7-8722af73800a.mov

I had to initially change `recording.py` to get the script to start (was complaining about wrong channel count since its a mono mic):
```
    recording = sd.rec(int(secs * 48000), samplerate=48000, channels=1)
```

And added some prints: 
```
recording = sd.rec(int(0 * 48000), samplerate=48000, channels=1)

def record (secs=4):
    print("[recorder.py] Recording...")
    global recording
    recording = sd.rec(int(secs * 48000), samplerate=48000, channels=1)

def stop():
    print("[recorder.py] Stopping recording!")
    global recording
    sd.stop()
    os.system('rm speaker.wav')
    write('speaker.wav', 48000, recording)
```

I've tried changing the `4096` value in `recorder.py` with no real change:
```
    soundData = data.read(4096)
```

I'm assuming it has to be something wonky with the sample rate and processing rate, but I don't have enough contextual knowledge here to know, and ChatGPT is only getting me so far haha.

Any thoughts?

**Comment by appvoid** [comment]
For some weird reason it's using fp16 on cpu which is not supported, that's weird...

Anyway, I think you are having an overflow common problem, it usually happens when the device doesn't processes data faster enough. The solution could be using:

`soundData = data.read(4096,exception_on_overflow=False)`

Haven't tested myself yet but give it a try and let me know if it fix your issue.

**Comment by joegoldin** [comment]
Thanks for the reply! I hadn't even started to look at the FP16 issue which is odd. 

That `exception_on_overflow=False` did resolve the crashes, so thank you! I'm getting pretty poor performance though, which could have something to do with the FP16 issue.

Regardless, appreciate the fix :)
